"""Application configuration and performance defaults."""

APP_NAME = "BiTS"
APP_VERSION = "15.3"
APP_TITLE = f"{APP_NAME} - Bivariate Tomography Segmentation"

DEFAULT_BINS = 256
MAX_BINS = 512
MIN_BINS = 64
DEFAULT_HISTOGRAM_CACHE_SIZE = 10
DEFAULT_SEGMENTATION_CACHE_SIZE = 5

USE_GPU_DEFAULT = True
SUBSAMPLE_THRESHOLD_GB = 16
MEMMAP_THRESHOLD_GB = 8
HISTOGRAM_CHUNK_VOXELS = 4_000_000
KMEANS_MAX_FIT_SAMPLES = 250_000
KMEANS_PREDICTION_CHUNK_SIZE = 2_000_000
RF_MAX_SAMPLES_PER_CLASS = 100_000
RF_PREDICTION_CHUNK_SIZE = 1_000_000

DEFAULT_FPS = 10
MAX_FPS = 60
MIN_FPS = 1

SUPPORTED_TIFF_EXTENSIONS = [".tif", ".tiff", ".TIF", ".TIFF"]
SUPPORTED_EXPORT_FORMATS = ["TIFF", "HDF5", "NumPy"]

ROI_COLOR = "#00FF00"
SEGMENTATION_OVERLAY_COLOR = "#FF0000"
SEGMENTATION_OVERLAY_ALPHA = 0.3
PROGRESS_UPDATE_INTERVAL_MS = 100
